### ISSUE TITLE
The multibyte role `short_description` causes warning "Title underline too short."

### ISSUE THREAD

**Issue by akira6592** [ansible-community/antsibull-docs#228]
The multibyte role `short_description` causes warning "Title underline too short."

`argument_specs.yml`: 

```yaml
---
argument_specs:
  main:
    short_description: short description of Main entry point for テストロール
    description:
      - description of Main entry point for テストロール
    author:
      - akira6592
    options:
      myapp_int:
        type: "int"
        required: false
        default: 42
        description:
          - "The integer value, defaulting to 42."
```

```sh
% dest/build.sh

...(omit)...
/Users/akira/ansible/dest/rst/collections/local/mycollection/myapp_role.rst:19: WARNING: Title underline too short.

local.mycollection.myapp role -- short description of Main entry point for テストロール
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/Users/akira/ansible/dest/rst/collections/local/mycollection/myapp_role.rst:41: WARNING: Title underline too short.

Entry point ``main`` -- short description of Main entry point for テストロール
------------------------------------------------------------------------

...(omit)...
```

It is not only role `short_description`, but maybe also other `short_description`.
