### ISSUE TITLE
Linter: prevent option/return value/... names which only differ by case

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/antsibull-docs#291]
For example, the `cisco.dnac.discovery` module has parameters:
```yaml
  snmpROCommunity:
    description: SNMP RO community of the devices to be discovered.
    type: str
  snmpRoCommunity:
    description: SNMP RO community of the devices to be discovered.
    type: str
```
and
```yaml
  snmpROCommunityDesc:
    description: Description for SNMP RO community.
    type: str
  snmpRoCommunityDesc:
    description: Description for SNMP RO community.
    type: str
```
These should likely be aliases of each other, instead of being separate parameters.
