### ISSUE TITLE
Adding more than one section in `extra-docs.yml` results in no sections included in output.

### ISSUE THREAD

**Issue by briantist** [ansible-community/antsibull-docs#30]
I have a docsite with `extra-docs.yml` like so:

```yaml
---
sections:
  - title: Guides
    toctree:
      - filter_guide
      - user_guide
      - migration_hashi_vault_lookup
      - about_hashi_vault_lookup
      - lookup_guide
      - contributor_guide
      - localenv_developer_guide
```

If I try to add new page `new_thing` to the existing guides section, it works fine:

```yaml
---
sections:
  - title: Guides
    toctree:
      - filter_guide
      - user_guide
      - new_thing
      - migration_hashi_vault_lookup
      - about_hashi_vault_lookup
      - lookup_guide
      - contributor_guide
      - localenv_developer_guide
```

If I try to add that page to a new, additional section, **neither of the two sections are produced in the output**:

```yaml
---
sections:
  - title: New Things
    toctree:
      - new_thing
  - title: Guides
    toctree:
      - filter_guide
      - user_guide
      - migration_hashi_vault_lookup
      - about_hashi_vault_lookup
      - lookup_guide
      - contributor_guide
      - localenv_developer_guide
```

If I remove the original section, and just include the new one, then the new one shows up as expected:

```yaml
---
sections:
  - title: New Things
    toctree:
      - new_thing
```

---

I've looked through the code a bit, but was not able to figure out where the issue might be.

I should add that there are no errors or warnings when this happens, not even `WARNING: document isn't included in any toctree` shows up.
